### ISSUE TITLE
handling temporary session_id 

### ISSUE THREAD

**Issue by deinelieblings** [Viva-con-Agua/drops#103]
If an User access to an MS they need to provide an own temporary session.
This session contains a session_id as representation of an sign in process.
The id will send in the redirect URL by parameter:
drops.url.de/redirect/clientid/:temp_id  
Drops store the temp_id in the access_token. So the MS can match the drops session with the user_session after the OAuth handshake is finish.

**Comment by johannsell** [comment]
*  Temporary session id will be sent as paramter on redirect to login
*  Redirect after Login should go there: 
`pool.vivaconagua.org/userlogin/?&sessionId=<temporarySessionId>&userId=<userId>&dropsSessionId=<dropsSessionID>`
*  Entry point for authorization code on Pool 1: 
`pool.vivaconagua.org/useraccess/?sessionId=<temporarySessionId>&authorizationCode=<authorizationCode>`

**Comment by johannsell** [comment]
idle - further discussion with Tobi required. I'm pretty sure we don't need to send temp session identifier and everything else (user identification happens during OAuth 2 handshake - no need to code it into Redirects).

Will be discussed on 2017-11-17.

**Comment by johannsell** [comment]
Temp Session ID has to be send to the Pool 1 after login (on redirect to the landing page - see #111 )

--> don not use the play session mechanism!

**Comment by johannsell** [comment]
Rejected, since requirement is solved another way.
