### ISSUE TITLE
Send new registered user to Pool 1

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/drops#106]
Using a webservice URL Pool² has to send all recently registered user to Pool 1.

@TobiKaestle: URL and data structure are needed. ;)

**Comment by johannsell** [comment]
Deadline: 15.11.2017

**Comment by TobiKaestle** [comment]
Structur:
$_POST['hash']
$_POST['user'] = 
{
    'user_login' => 'exampleuser',
    'user_nicename' => 'example-user',
    'user_email' => 'example@user.de',
    'display_name' => 'Example U.',
    'user_name' => 'Example User',
    'usermeta' => {
        'nickname' => 'Example User',
        'first_name' => 'Example',
        'last_name' => 'User',
        'mobile' => '123456789',
        'residence' => 'ExampleCity',
        'birthday' => '585352800',
        'gender' => 'male',
        'nation' => '40',
        'city' => '1',
        'region' => '1'
    }
}

pool.vivaconagua.org/usercreate/

**Comment by johannsell** [comment]
@TobiKaestle I've implemented a first version and would like to test it now. Can you give me the URL to Pool 1 testserver, please? We can exchange the needed hash using the Keepass file in Dropbox.
