### ISSUE TITLE
User import from external tools

### ISSUE THREAD

**Issue by deinelieblings** [Viva-con-Agua/drops#107]
For a SignIn with a Pool account in Pool² the passwords have to be recreated. Problem here is that the Pool still uses md5-hash for password hashing, so Drops can not resolve the passwords.

<del>To solve this problem, a user of Pool must register their account with Drops:
We can import all data of the User in Drops, except the password.
We can flag every Pool 1 user in Drops:
Pool1_User: {true, false}</del> 
see https://github.com/Viva-con-Agua/drops/issues/113

<del>The handleStartSignUp function checks if an email is already registered. Here we can add a function that checks if the user has a Pool account, but no Pool² password. </del>

see comments

Thus, we can at this point a reduced SignUp:
     1) User gets a mail asking to change his/her password.
     2) The (existing Pool 1 imported) profile is extended by the new password.
     3) User can now SignIn in Pool² and we can remove the Pool 1 flag.

Thus, we need to implement three functions: import user stubs from Pool 1; a view allow to enter an email address (considering an existing Pool 1 account); and a function that implements the workflow described before.

**Comment by johannsell** [comment]
The new function should be visible for 6 months. After that period of time, the function has to be unvisible and at least removed AND all users which still have the flag have to be removed from database (see email conversation between @ansgarmax and @johannsell from 2017-10-30 and 2017-11-01).

**Comment by deinelieblings** [comment]
Instead of editing functions, we will implement a new function that will provide the necessary functions for the Pool1 account migration. Further, the user must be identifiable via his Pool1 
username.

**Comment by johannsell** [comment]
Edit: We need a function to set a new password (re-use function of password reset) and maybe new interface elements (buttons, emails, etc.) to init the setup of the password. But we DON'T need functions to import data from Pool 1. To do this, we have to write external scripts that import data. 

Import of Pool 1 data will (hopefully) be done only once, so I hope we don't have to hold code for this purpose inside our tool. ;)

**Comment by johannsell** [comment]
The new password setup workflow is also needed for import of users using the webservice. Thus, it should be more general: 
(0) All imported users should be marked as "not confirmed" (use existing flag)
(1) There should be a button saying: "Hello, I am an existing user, but I have no password yet"
(2) If the user selects the button s/he is able to enter an email address (or an username) and a new form is shown allowing to enter a new password. 
(3) After all, the confirmation mail will be sent

**Comment by deinelieblings** [comment]
due to some considerations, the workflow is changed:
(1) After the login a link is generated with which a user can set a new password
(2) The link will be sent via email and the user will be informed on the page after the login
      - The link is valid for 24 hours
      - a separate database table is created for the link store
            {id, link, token} -> {User}
(3) User click link and can change password
     - If a user clicks on an invalid link, they will be notified via the page
(4) confirmation email  -> drop the table

**Comment by johannsell** [comment]
@deinelieblings are you sure you need a `link` inside the database? I would suggest `id`, `user_id` and `token` are useful columns. The `link` (in case it's an URL) should be hard-coded in `routes`.

Additionally, after confirming the new Password using mail should not drop the table, but remove the row considering the `user_id`.

Last note: We also want to use the table for flagging the Pool 1 user. Thus, all user imported from Pool 1 should be referenced in this table. Before the user initiates the Password Setup, the token field in `Null`.
