### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by deinelieblings** [Viva-con-Agua/drops#113]
For database migration, there are two options:
1: Users are searched for the signup in Pool1 and then created in drops.
   More complex implementation, but we get so inactive users well filtered.  
   Pool1 implements OAuth provider functions to get the users.
2: Migrate the database completely
  Users must be marked, see https://github.com/Viva-con-Agua/drops/issues/107

**Comment by johannsell** [comment]
We will migrate all users of Pool 1. Additionally, we have to mark them as "not confirmed" (see comments at #107). I think thats enough, so this has not to be implemented. Instead we could use the webservice import (user create)?

**Comment by johannsell** [comment]
@ottmann We need the database schemas, so please create the schemas at first and try to link the commit here.

**Comment by johannsell** [comment]
@ottmann schema are no longer required

**Comment by deinelieblings** [comment]
@TobiKaestle we need the pool1 database to test the function and make the migration.

**Comment by johannsell** [comment]
Rejected, since this shouldn't be part of the drops code base. Instead, @deinelieblings implemented a python script doing the job (See Asana for more information).
