### ISSUE TITLE
OAuth Database bug 

### ISSUE THREAD

**Issue by deinelieblings** [Viva-con-Agua/drops#213]
after adding the pool1 docker as oauthclient, the redirect don't work. 
Problem is a database primary key trouble. 
Duplicate entry '[cryptic stuff]-wp_pool' for key 'PRIMARY' . 
So i think there is some trouble with storing the Token into database or with the temporary created authorization_code

**Comment by deinelieblings** [comment]
@ottmann how to fix?

**Comment by johannsell** [comment]
@ottmann @deinelieblings let us brainstorm tomorrow. @ottmann should have time to work for his studies. We will fix this together. 🙂

**Comment by deinelieblings** [comment]
close with https://github.com/Viva-con-Agua/drops/pull/216
