### ISSUE TITLE
RESTful SignUp action

### ISSUE THREAD

**Issue by gottemeyer** [Viva-con-Agua/drops#228]
[arise](https://github.com/Viva-con-Agua/arise) needs an endpoint for SignUp. This SignUp action has top be equal to the current SignUp action implemented in the `AuthController`, except it has to receive JSON data and handles responses using JSON. It's required by [arise #1](https://github.com/Viva-con-Agua/arise/issues/1).

Please enter route and expected format as a comment at the issue.

**Comment by deinelieblings** [comment]
The function already exists:
/rest/user/create 
```
 CreateUserBody(
     email: String,
     firstName : String,
     lastName: String,
     mobilePhone: String,
     placeOfResidence: String,
     birthday: Long,
     sex: String,
     password: Option[String], //Password is optional, perhaps its necessary to set the pw on the first login
     profileImageUrl: Option[String]
  )
```
