### ISSUE TITLE
Organizations are configurable

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/drops#32]
Organizations consist of:
*  Name
*  Address

(Example data will be sent Ansgar)

A CRUD for organizations is needed, only admins have the right to change these data, while employees are able to see the list of organizations.

**Comment by johannsell** [comment]
@ansgarmax: Organizations defined by users of Drops? Or CiviCRM?

(e.g. "Viva con Agua de St. Pauli e.V.", "Arts creates Water", etc.)

No matter where it will be defined, organizations will be saved in CiviCRM.

**Comment by ansgarmax** [comment]
@johannsell Definition should go both sides calles "counterflow-principle" Does this one help?

**Comment by johannsell** [comment]
@ansgarmax okay, cool. Thx!

**Comment by deinelieblings** [comment]
https://github.com/Viva-con-Agua/drops/pull/229
