### ISSUE TITLE
Delete failed

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/drops#333]
One user has reported that s/he could not delete their user. One suggestion: It could be, that we have an error using the Pool 1 API. Thus, on error, Drops maybe not deletes a user.

**Comment by deinelieblings** [comment]
Why drops don't delete a User if Pool1 Api is not working?

**Comment by johannsell** [comment]
Yes, you're right, that is not the problem. I thought that Drops maybe waits until the Pool 1 has successfully deleted the entry, but looking at https://github.com/Viva-con-Agua/drops/blob/ffe6a24f8f8694f10f0317af7d52da89a12f55f1/app/services/UserService.scala#L129 you can see: It's the other way around.

**Comment by deinelieblings** [comment]
The problem was the OauthTokens, I forgot to consider them
