### ISSUE TITLE
Task Object

### ISSUE THREAD

**Issue by deinelieblings** [Viva-con-Agua/drops#47]
Object that represents a task.

**Comment by johannsell** [comment]
Inclusive associated TaskDAO (trait + Impl for chosen DB connection)

**Comment by johannsell** [comment]
![erddiagramtasks-civicrm](https://user-images.githubusercontent.com/5207572/28110395-90d06d12-66f2-11e7-80b8-77425ca0cea3.png)

--> Data should be saved in a relational DB (e.g. MariaDB)

**Comment by johannsell** [comment]
If a supporter creates a task, s/he is only able to assign Access Rights that are already associated to the supporter (by roles or other tasks).

**Comment by johannsell** [comment]
Also Update, Read (a view) and Delete should be possible:
Attention: If a user removes an Access Right a warning should be shown, if the Access Right is not associated to the user by any other task / role AND another warning, if it is not associated to any other crew member.

**Comment by ottmann** [comment]
@johannsell i think, we need also a relation between tasks and crews to refere tasks which have no assigned supporter

**Comment by johannsell** [comment]
This issue contains:
* REST API für Create, read von Tasks
* Task Model + DAO + Database Evolutions
* Access Rights Model + DAO + Database Evolutions
* Read UI Tasks

Open Todos here:
* Refactoring using Slick
