### ISSUE TITLE
Relations between Tasks and Access Rights

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/drops#70]
Access Rights should be assignable to tasks. This issue contains everything to make it work, except the user interface, since the concept is missing.

**Comment by ottmann** [comment]
research on update cascade and on delte cascade

**Comment by ottmann** [comment]
@johannsell I have implemented a proposal for an api call to get an task with all related access rights.
It works - but i doubt this is not ne best solution. Whats your opinion?

https://github.com/Viva-con-Agua/drops/commits/feature/70_accessRight_task_relation

**Comment by johannsell** [comment]
For our first steps we won't need a function  to receive all access rights for a specific task. We need a function to receive all access rights for a given user. Connecting users and tasks will be the first step. ;)

But after all we aim to implement a complete and powerful RESTful interface, since we're not able to predict the future. Therefore, the new action is fine and should remain unchanged.

**Comment by ottmann** [comment]
Use Services instead of controller to combine DAOs
