### ISSUE TITLE
RESTful interface to request access rights

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/drops#73]
Micorservices should be able to request a list of access rights. Those lists have to be filtered by a users ID and a microservice ID. The interface returns a list of URIs as a JSON.

**Comment by ottmann** [comment]
Sample call
`http://localhost:9000/rest/access?q=accessright.service.=_AND_user.id.=&f={"accessRight":{"service":"drops"},"user":{"id":"e831ed78-5d66-411e-af39-eaa3d0d72a76/task"}}`

**Comment by ottmann** [comment]
User on big join over UserTask, Task, TaskAccessRight and AccessRight Table
